/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Applicant {
  city: string | null;
  created_at: Generated<Date>;
  designation: Generated<string>;
  dob: Date;
  email: string;
  first_name: string;
  full_address: string | null;
  gender: "female" | "male" | "other";
  id: Generated<number>;
  is_deleted: Generated<number | null>;
  last_name: string;
  phone: string;
  relationship_status: "committed" | "single" | null;
  state: Generated<string | null>;
  zip_code: string | null;
}

export interface Technologies {
  applicant_id: number;
  created_at: Generated<Date | null>;
  id: Generated<number>;
  is_deleted: Generated<number>;
  label: string;
  proficiency: "beginner" | "expert" | "intermediate" | null;
  updated_at: Generated<Date | null>;
}

export interface DB {
  applicant: Applicant;
  technologies: Technologies;
}
